In [306]:
# this is much more hand-craft version. 

import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [307]:
def subm(A, i, j):
    n = A.shape[0]
    M = np.empty((n-1)*(n-1))
    inc = 0
    for row_iter in range(n):
        for col_iter in range(n):
            if row_iter != i and col_iter !=j:
                M[inc] = A[row_iter][col_iter]
                inc = inc + 1
    M = np.array(M.reshape((n-1,n-1)))
    return M

In [308]:
def detm(A):
    det = 0
    if A.shape[0] > 2:
        for i in range(A.shape[0]):
            det = det + A[i][0] * detm(subm(A,i,0)) * (-1)**i
    elif A.shape[0] == 2:
        det = A[0][0]*A[1][1] - A[0][1]*A[1][0]
    return det

In [309]:
def cftr(A,i,j):
    return (-1)**(i+j) * detm(subm(A,i,j))

In [310]:
def adjt(A):
    C = np.zeros((A.shape))
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            C[i][j] = cftr(A,i,j) 
    return C.T

In [311]:
def ivrs(A):
    return adjt(A) / detm(A)

In [312]:
B = np.array([[3,1,-1],[2,-2,0],[1,2,-1]])
print(ivrs(B))
print(B@ivrs(B))

[[ 1.  -0.5 -1. ]
 [ 1.  -1.  -1. ]
 [ 3.  -2.5 -4. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
